if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
	eval $(dbus-launch --exit-with-session --sh-syntax)
fi
systemctl --user import-environment DISPLAY XAUTHORITY
if command -v dbus-update-activation-environment >/dev/null 2>&1; then
        dbus-update-activation-environment DISPLAY XAUTHORITY
fi

xrdb merge ~/.Xresources
if [ $(uname -n) == "virtuoso" ]; then
	xrandr --output DisplayPort-0 --mode 1920x1080 --rate 144
fi
